---
title: "Mixed Model EEG fMRI"
output:
  html_document:
    df_print: paged
---

# Import Packages

```{r}
library(readxl) # read excel
library(emmeans) # for post hoc tests
library(dplyr)
library(tidyr)
library(datawizard)
library(lme4)
library(lmerTest) 
library(effects) 
library(readr)
library(ggplot2)
library(afex)
```

# Load dataset

```{r}
data <- read_excel("C:/Users/juhoffmann/Desktop/Git/UnconsciousBias/data/regressors_10_Cluster_MixedModel.xlsx", 
    col_types = c("numeric", "numeric", "text", "text", "numeric", "numeric", "numeric", "numeric", "numeric"))

head(data)
```


```{r}
data <- data
plot(density(data$Cluster_value),main="Cluster Value Density estimate of data")

```


# Check for distribution type

```{r}
x <- data$Cluster_value+100
den <- density(x)
dat <- data.frame(x = den$x, y = den$y) 

#Fit distributions
library(fitdistrplus)
fit.weibull <- fitdist(x, "weibull")
fit.normal <- fitdist(x,"norm")
fit.gamma <- fitdist(x, "gamma", lower = c(0, 0))

# Compare fits graphically
plot.legend <- c("Weibull", "Gamma","Normal")
par(mfrow = c(2, 2)) #show 4 pictures
denscomp(list(fit.weibull, fit.gamma, fit.normal), fitcol = c("red", "blue","green"), legendtext = plot.legend)
qqcomp(list(fit.weibull, fit.gamma, fit.normal), fitcol = c("red", "blue","green"), legendtext = plot.legend)
cdfcomp(list(fit.weibull, fit.gamma, fit.normal), fitcol = c("red", "blue","green"), legendtext = plot.legend)
ppcomp(list(fit.weibull, fit.gamma, fit.normal), fitcol = c("red", "blue","green"), legendtext = plot.legend)
```
## factorise variables

```{r}
data <- data%>%
  mutate(gender = as.factor(gender_f1_m2)) %>%
  mutate(group = as.factor(group_MDD1_HC2)) %>%
  mutate(emotion = as.factor(emotion)) %>%
  mutate(consciousness = as.factor(consciousness)) %>%
  mutate(cluster_number = as.factor(Cluster_number))

```


## estimate model

```{r}
Model <- lmer(Cluster_value ~ group*emotion*consciousness + gender + cluster_number 
                       + (1|bids_number),
                       data = data)
anova_Model<-anova(Model, type = 3, ddf= "Kenward-Roger")
anova_Model
```

```{r}
sjPlot::tab_model(Model)
sjPlot::plot_model(Model, type = "diag")
```

## Post Hoc tests

```{r}
eff.cluster       <- emmeans(Model, pairwise ~ cluster_number,adjust ="bonferroni")
eff.consciousness <- emmeans(Model, pairwise ~ consciousness)

```

```{r}
eff.cluster
eff.consciousness
```

## plot effects

```{r}
cluster <-  afex_plot(Model, x = "cluster_number", 
            id = "bids_number", dodge = 0.8, 
            data_geom = geom_violin, 
            mapping = c("linetype", "fill"),
            error_arg = list(width = 0.2),
            legend_title = "cluster number",
            data_arg = list(width = 0.5)) + 
    #ggpubr::theme_pubr() + 
    scale_fill_manual(values = c("happy" = "greenyellow", "neutral" = "lightblue", "sad"= "orange")) + 
    theme(legend.position="none") +
  labs(y = "cluster value", x = "cluster number")

  
conscious<-  afex_plot(Model, x = "consciousness", 
            id = "bids_number", dodge = 0.8,
            data_geom = geom_violin, 
            mapping = "fill",
            error_arg = list(width = 0.2),
            data_arg = list(width = 0.5)) + #ggpubr::theme_pubr() + 
    scale_fill_manual(values = c("conscious" = "grey", "unconscious" = "white")) +
    theme(legend.position="none") + 
    labs(y = "cluster value", x = "")

```

```{r}
cluster
```

```{r}
conscious
```

```{r}
# Combine plots into a grid
combined_plots1 <- cowplot::plot_grid(cluster, conscious,
                            labels = c("A", "B"),
                            ncol = 1,nrow = 2)

# Display the combined plots
print(combined_plots1)
```




# Calculate alternative models with less interactions

```{r}
Model.c <- lmer(Cluster_value ~ consciousness*emotion 
                + consciousness*group 
                + emotion*group
                + gender + cluster_number 
                       + (1|bids_number),
                       data = data)
anova_Model<-anova(Model.c, type = 3, ddf= "Kenward-Roger")
anova_Model
```