%-----------------------------------------------------------------------
% Job saved on 17-Oct-2022 10:11:02 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown

clear all

addpath '/bif/storage/storage1/projects/emocon/Scripts/EEG_fMRI_Analysis'   
Data_Path = fullfile('/bif/storage/storage1/projects/emocon/FirstLevel_Primer/BackwardMask/'); 
Subjects = {
'sub-004',...
'sub-006',...
'sub-007',...
'sub-008',...
'sub-009',...
'sub-010',...
'sub-011',...
'sub-012',...
'sub-014',...
'sub-015',...
'sub-017',...
'sub-018',...
'sub-019',...
'sub-021',...
'sub-022',...
'sub-024',...
'sub-025',...
'sub-026',...
'sub-027',...
'sub-031',...
'sub-032',...
'sub-033',...
'sub-034',...
'sub-035',...
'sub-036',...
'sub-037',...
'sub-038',...
'sub-039',...
'sub-040',...
'sub-041',...
'sub-043',...
'sub-044',...
'sub-045',...
'sub-046',...
'sub-047',...
'sub-049',...
'sub-051',...
'sub-052',...
'sub-053',...
'sub-054',...
'sub-056',...
'sub-057',...
'sub-059',...
'sub-062',...
'sub-064',...
'sub-065',...
'sub-066',...
'sub-068',...
'sub-069',...
'sub-070',...
'sub-071',...
'sub-072',...
'sub-073',...
'sub-074',...
'sub-075',...
'sub-076',...
'sub-077',...
'sub-079',...
'sub-081',...
'sub-082',...
'sub-083',...
'sub-084',...
'sub-085',...
'sub-086',...
'sub-088',...
'sub-089',...
'sub-090',...
'sub-091',...
'sub-093',...
'sub-096',...
'sub-097',...
'sub-098',...
'sub-099',...
'sub-100',...
'sub-102',...
'sub-103',...
'sub-104',...
'sub-106',...
'sub-107',...
'sub-108',...
'sub-109',...
'sub-110',...
'sub-111',...
'sub-112',...
'sub-113',...
'sub-114',...
'sub-115',...
'sub-116',...
'sub-117',...
'sub-118',...
'sub-120',...
'sub-122',...
'sub-123',...
'sub-124',...
'sub-125',...
'sub-126',...
'sub-127',...
'sub-128',...
'sub-129',...
'sub-130',...
'sub-131'};



for i = 1:numel(Subjects)                                                    %for every 'subject in the HC directory
   subName = Subjects{i};  
    
   happy_unconscious{i,:} = fullfile(Data_Path, subName,'con_0001.nii,1');
   sad_unconscious{i,:} = fullfile(Data_Path, subName,'con_0002.nii,1');
   neutral_unconscious{i,:} = fullfile(Data_Path, subName,'con_0003.nii,1');
   
   happy_conscious{i,:} = fullfile(Data_Path, subName,'con_0004.nii,1');
   sad_conscious{i,:} = fullfile(Data_Path, subName,'con_0005.nii,1');
   neutral_conscious{i,:} = fullfile(Data_Path, subName,'con_0006.nii,1');

end

scans = vertcat(happy_unconscious,sad_unconscious,neutral_unconscious,happy_conscious,sad_conscious,neutral_conscious);


%%
matlabbatch{1}.spm.stats.factorial_design.dir = {'/bif/storage/storage1/projects/emocon/SecondLevel/EEG_fMRI/Regression_N170/'};

% load scans
matlabbatch{1}.spm.stats.factorial_design.des.mreg.scans = scans;
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov = struct('c', {}, 'cname', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.des.mreg.incint = 1;              % 1 = include intercept
matlabbatch{1}.spm.stats.factorial_design.cov = struct('c', {}, 'cname', {}, 'iCFI', {}, 'iCC', {});

% load regressor
matlabbatch{1}.spm.stats.factorial_design.multi_cov.files = {'/bif/storage/storage1/projects/emocon/Scripts/EEG_fMRI_Analysis/regressor_2.txt'};
matlabbatch{1}.spm.stats.factorial_design.multi_cov.iCFI = 1;               % interaction; 1 = None, 2 = with factor 1, 3 = with factor 2 etc.
matlabbatch{1}.spm.stats.factorial_design.multi_cov.iCC = 1;                % 1 = overall mean, 2 = factor 1 mean, 3 = factor 2 mean, 4 = factor 3 mean, 5 = no centering
matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none = 1;           % threshold masking
matlabbatch{1}.spm.stats.factorial_design.masking.im = 1;                   % implicit masking
matlabbatch{1}.spm.stats.factorial_design.masking.em = {''};                % explicit masking
matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm = 1;

% estimate created Batch
matlabbatch{2}.spm.stats.fmri_est.spmmat = {'/bif/storage/storage1/projects/emocon/SecondLevel/EEG_fMRI/Regression_N170/SPM.mat'};
matlabbatch{2}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;


% run created Batch
spm_jobman('initcfg');
spm_jobman('run', matlabbatch);

